apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-local-db-ssd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-db-ssd-rwo
  resources:
    requests:
      storage: 50Gi
