apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-path-provisioner-db-ssd-service-account
  namespace: local-db-ssd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: local-path-provisioner-db-ssd-role
  namespace: local-db-ssd
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: local-path-provisioner-db-ssd-role
rules:
  - apiGroups: [""]
    resources: ["nodes", "persistentvolumes", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["create", "delete", "patch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: local-path-provisioner-db-ssd-bind
  namespace: local-db-ssd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: local-path-provisioner-db-ssd-role
subjects:
  - kind: ServiceAccount
    name: local-path-provisioner-db-ssd-service-account
    namespace: local-db-ssd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-path-provisioner-db-ssd-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: local-path-provisioner-db-ssd-role
subjects:
  - kind: ServiceAccount
    name: local-path-provisioner-db-ssd-service-account
    namespace: local-db-ssd
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-path-config
  namespace: local-db-ssd
data:
  config.json: |-
    {
      "nodePathMap":[
        {
          "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
          "paths":[]
        },
        {
          "node":"node3",
          "paths":["/mnt/db-ssd"]
        }
      ]
    }
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      priorityClassName: system-node-critical
      tolerations:
        - key: node.kubernetes.io/disk-pressure
          operator: Exists
          effect: NoSchedule
      containers:
        - name: helper-pod
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c", "trap exit TERM; sleep infinity & wait"]
  setup: |-
    #!/bin/sh
    set -eu
    mkdir -p "$VOL_DIR"
  teardown: |-
    #!/bin/sh
    set -eu
    rm -rf "$VOL_DIR"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-path-provisioner-db-ssd
  namespace: local-db-ssd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-path-provisioner-db-ssd
  template:
    metadata:
      labels:
        app: local-path-provisioner-db-ssd
    spec:
      serviceAccountName: local-path-provisioner-db-ssd-service-account
      containers:
        - name: local-path-provisioner
          image: rancher/local-path-provisioner:v0.0.31
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG_MOUNT_PATH
              value: /etc/config/
          command:
            - local-path-provisioner
            - --debug
            - start
            - --config
            - /etc/config/config.json
            - --configmap-name
            - local-path-config
            - --configmap-namespace
            - $(POD_NAMESPACE)
            - --service-account-name
            - local-path-provisioner-db-ssd-service-account
            - --provisioner-name
            - homelab.jacobagtyler.com/local-db-ssd
            - --helper-image
            - busybox:1.36
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config/
      volumes:
        - name: config-volume
          configMap:
            name: local-path-config
