apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-db-ssd-rwo
provisioner: homelab.jacobagtyler.com/local-db-ssd
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
