apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero-install
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://vmware-tanzu.github.io/helm-charts
      chart: velero
      targetRevision: 11.4.0
      helm:
        valueFiles:
          - $values/K8S/Velero/install-values.yaml
    - repoURL: https://github.com/JacobAGTyler/HomeLab.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true

