apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/JacobAGTyler/HomeLab.git
    targetRevision: HEAD
    path: K8S/Velero/config
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - SkipDryRunOnMissingResource=true

