apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: lbd-apps
  namespace: argocd
spec:
  description: LBDistrictScouts application workloads
  sourceRepos:
    - https://github.com/LBDistrictScouts/DistrictCoreData.git
    - https://github.com/LBDistrictScouts/DistrictCMS.git
    - https://github.com/LBDistrictScouts/DistrictBadges.git
    - https://github.com/LBDistrictScouts/DistrictTeam.git
    - https://github.com/LBDistrictScouts/EventBookingBackend.git
  destinations:
    - namespace: district-badges-test
      server: '*'
    - namespace: district-badges-prod
      server: '*'
    - namespace: district-cms-dev
      server: '*'
    - namespace: district-cms-prod
      server: '*'
    - namespace: district-core-data
      server: '*'
    - namespace: district-team-test
      server: '*'
    - namespace: district-team-prod
      server: '*'
    - namespace: event-booking
      server: '*'
    - namespace: event-booking-test
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
