apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  description: Homelab infrastructure services and cluster configuration
  sourceRepos:
    - https://github.com/JacobAGTyler/HomeLab.git
    - ghcr.io/databasus/charts
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
