apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  description: Homelab infrastructure services and cluster configuration
  sourceRepos:
    - https://github.com/JacobAGTyler/HomeLab.git
  destinations:
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: local-db-ssd
      server: https://kubernetes.default.svc
    - namespace: metallb-system
      server: https://kubernetes.default.svc
    - namespace: truenas-nfs-provisioner
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

