apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: databasus-tls
  namespace: databasus
spec:
  secretName: databasus-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - databasus.jacobagtyler.com
