apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kestra-ingress
  namespace: kestra
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - kestra.jacobagtyler.com
    secretName: kestra-tls
  rules:
  - host: kestra.jacobagtyler.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kestra-ui-service
            port:
              number: 8080