apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: jacob@jacobagtyler.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: route53-issuer-account-key
    solvers:
    - dns01:
        route53:
          region: us-east-1
          hostedZoneID: Z1V49N7OG26NA3
          accessKeyIDSecretRef:
            name: prod-route53-credentials-secret
            key: access-key-id
          secretAccessKeySecretRef:
            name: prod-route53-credentials-secret
            key: secret-access-key