apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prod-route53-credentials-secret
  namespace: cert-manager
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/Infrastructure/items/K3S Cert Manager - AWS IAM Credentials
