apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  annotations:
    metallb.io/ip-allocated-from-pool: main-pool
    metallb.universe.tf/loadBalancerIPs: 10.3.0.105
spec:
  type: LoadBalancer
