apiVersion: v1
kind: Secret
metadata:
  name: jt-waf-secret
  namespace: bunkerweb
type: Opaque
data:
  database-uri: bWFyaWFkYitweW15c3FsOi8vanQtd2FmLW1hcmlhZGItdXNlci03eDl4MTpxZUlwQmN0ZytuUWNmVU1aV2oyeVlyQllqd3JCdWRrSjEzV0ZDNzVlNTdFPUBtYXJpYWRiLWJ3LWp0LXdhZi5idW5rZXJ3ZWIuc3ZjLmNsdXN0ZXIubG9jYWw6MzMwNi9kYg==
  redis-username: anQtd2FmLXJlZGlzLXVzZXItODM3eDk=
  redis-password: VVgwTVM3b1NGa045Y3NJaUhHSHZic2d5OWEyOSt6Szdib2lXUEVYK3hVUT0=
  admin-username: anQtd2FmLWFkbWluLXVzZXIteG0xOWo=
  admin-password: MTJhbE9Vd2orS1lvZjA4Qi96WmkxdG9yaG1EM2Q2Wm45TVB6RWYxb1RqST0=
  flask-secret: ZklTdG1vRVlmUmg2a0RuTmxsMUNlaFp4V3FEN0tkZC9ucnF6aiswUUtGcz0=
  totp-secrets: cDZ4cW9ybVh5SDdnNEl3MnVPaXJnSnR0T1NZOElUK1pJNlZ6ZEJmbHBoQT0gNkd3b0c0Q2dKVEtjN29yVEhaSEh5WHBDbjBwR3ZKck4xYmkvMnhHZGtQST0gTExFSCswRlMxd3NobkRJQ2JIZURqNmc0aHFBTUpKUk9sd2NWZEYwQm9vQT0gQ1ZHQ01ITk1pMEp5a0NUL2VmYThqMkY5cklWcjVITHgraEtaVnFLK21EWT0gT1NUSlFtdXgvR1NWSmJNS0dxOE44SC9HcmhjZmxkaTV0MzhmbU1WMkhBZz0=
  mariadb-user: anQtd2FmLW1hcmlhZGItdXNlci03eDl4MQ==
  mariadb-password: cWVJcEJjdGcrblFjZlVNWldqMnlZckJZandyQnVka0oxM1dGQzc1ZTU3RT0=
