apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: homebox
  name: homebox-data
  namespace: homebox
spec:
  storageClassName: local-db-ssd-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
