apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.io/ip-allocated-from-pool: main-pool
    metallb.universe.tf/loadBalancerIPs: 10.3.0.109
  labels:
    app.kubernetes.io/name: homebox
  name: homebox
  namespace: homebox
spec:
  type: LoadBalancer
  ports:
    - name: web-http
      port: 80
      targetPort: web-http
    - name: web-https
      port: 443
      targetPort: web-https
  selector:
    app.kubernetes.io/name: homebox
