apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - homebox-certificate.yaml
  - homebox-nginx-configmap.yaml
  - homebox-data-persistentvolumeclaim.yaml
  - homebox-deployment.yaml
  - homebox-service.yaml
