apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Projects
  - projects/project-infrastructure.yaml
  - projects/project-lbd-apps.yaml

  # Infrastructure Applications
  - apps/cert-manager-config.yaml
  - apps/metallb-config.yaml
  - apps/storage-local-db-ssd.yaml
  - apps/storage-truenas-nfs.yaml

  # LBD Applications
  - apps/district-core-data.yaml

  # Secrets
  - secrets/repo-districtcoredata-secret.yaml
