apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager-config.yaml
  - metallb-config.yaml
  - storage-local-db-ssd.yaml
  - storage-truenas-nfs.yaml
  - velero-install.yaml
  - velero-config.yaml
