apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    metallb.io/address-pool: main-pool
spec:
  type: LoadBalancer
  ports:
    - name: web-http
      port: 80
      targetPort: web-http
    - name: web-https
      port: 443
      targetPort: web-https
  selector:
    app.kubernetes.io/name: homepage
