---
  - name: Configure SSH Key Security
    hosts: all
    become: true

    tasks:
      - name: Set Authorized Key taken from file
        authorized_key:
          user: ubuntu
          state: present
          key: "{{ ssh_pub_key }}"
