apiVersion: v1
kind: Secret
metadata:
  name: repo-creds-lbdistrictscouts
  namespace: argocd
  annotations:
    operator.1password.io/item-name: repo-creds-lbdistrictscouts
    operator.1password.io/item-path: vaults/Infrastructure/items/ArgoCD - LBD Repo Creds
  labels:
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
