apiVersion: v1
kind: Secret
metadata:
  name: repo-districtcoredata
  namespace: argocd
  annotations:
    operator.1password.io/item-name: repo-districtcoredata
    operator.1password.io/item-path: vaults/Infrastructure/items/ArgoCD - DistrictCoreData Repository
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque

