apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - namespace.yaml
  - deployment.yaml
  - widget-credentials-onepassworditem.yaml
  - manifests/hp-service.yml
  - homepage-certificate.yaml
  - manifests/hp-service-account.yml
  - manifests/hp-secret.yml
  - manifests/hp-cluster-role.yml
  - manifests/hp-cluster-role-binding.yml
configMapGenerator:
  - name: homepage-nginx
    files:
      - default.conf=nginx/default.conf
  - name: homepage-config
    files:
      - config/bookmarks.yaml
      - config/kubernetes.yaml
      - config/services.yaml
      - config/widgets.yaml
      - config/settings.yaml
      - config/docker.yaml
      - config/custom.css
      - config/custom.js
