apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: homepage-widget-credentials
  namespace: homepage
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/Infrastructure/items/homepage-widget-credentials
