- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: "cluster"
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true
- unifi_console:
    url: https://10.1.0.1
    username: "{{HOMEPAGE_VAR_UNIFI_USERNAME}}"
    password: "{{HOMEPAGE_VAR_UNIFI_PASSWORD}}"
- resources:
    backend: resources
    expanded: true
    cpu: true
    memory: true
