---
- name: Install K3S on the Servers
  hosts: all
  become: true
  gather_facts: true

  tasks:
      - name: Create Config Directory
        file:
            path: /etc/rancher/k3s
            state: directory
      - name: Create Config File
        template:
            src: config.yaml.j2
            backup: true
            dest: /etc/rancher/k3s/config.yaml
      - name: Download K3S Script
        get_url:
            url: https://get.k3s.io
            dest: /home/ubuntu/k3s.sh
      - name: Run Script
        sh:
            script: /home/ubuntu/k3s.sh

#        curl -sfL https://get.k3s.io | K3S_TOKEN=12345 sh -s - server --flannel-backend none