---
- name: Install K3S on the Servers
  hosts: all
  become: true
  gather_facts: true

  tasks:
      - name: Set the new hostname
        hostname:
          name: "{{ inventory_hostname }}"
        register: hostname_result
        changed_when: hostname_result.changed

      - name: Update /etc/hosts file
        lineinfile:
            path: /etc/hosts
            regexp: '127\.0\.1\.1\s+.*'
            line: "127.0.1.1   {{ inventory_hostname }}"
            state: present
        register: hosts_file_result
        changed_when: hosts_file_result.changed

      - name: Update /etc/hostname file
        lineinfile:
            path: /etc/hostname
            line: "{{ inventory_hostname }}"
            state: present
        register: hostname_file_result
        changed_when: hostname_file_result.changed

      - name: Create Config Directory
        file:
            path: /etc/rancher/k3s
            state: directory

      - name: Create Composite Config Directory
        file:
            path: /etc/rancher/k3s/config.yaml.d
            state: directory

      - name: Remove Existing Config Files
        file:
            path: /etc/rancher/k3s/config.yaml
            state: absent

      - name: Create Base Config File
        template:
            src: base-config.yaml.j2
            backup: true
            dest: /etc/rancher/k3s/config.yaml.d/base-config.yaml
      
      - name: Create Primary Config File
        template:
            src: primary-config.yaml.j2
            backup: true
            dest: /etc/rancher/k3s/config.yaml.d/primary-config.yaml
        when: inventory_hostname == 'node1'

      - name: Create Non-Primary Config File
        template:
            src: non-primary-config.yaml.j2
            backup: true
            dest: /etc/rancher/k3s/config.yaml.d/non-primary-config.yaml
        when: inventory_hostname != 'node1'

      
      - name: Create Secondary Config File
        template:
            src: secondary-config.yaml.j2
            backup: true
            dest: /etc/rancher/k3s/config.yaml.d/secondary-config.yaml
        when: inventory_hostname in ['node2', 'node3']

      
      - name: Create Worker Config File
        template:
            src: worker-config.yaml.j2
            backup: true
            dest: /etc/rancher/k3s/config.yaml.d/worker-config.yaml
        when: inventory_hostname not in ['node1', 'node2', 'node3']
      
      - name: Download K3S Script
        get_url:
            url: https://get.k3s.io
            dest: /home/ubuntu/k3s.sh
      
      - name: Run Server Script
        shell:
            cmd: sh k3s.sh server
            chdir: /home/ubuntu/
        when: inventory_hostname in ['node1', 'node2', 'node3']

      - name: Run Worker Script
        shell:
            cmd: sh k3s.sh server
            chdir: /home/ubuntu/
        when: inventory_hostname not in ['node1', 'node2', 'node3']

  handlers:
    - name: Reboot the server
      reboot:
        msg: "Reboot initiated by Ansible for hostname change"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami

  post_tasks:
    - name: Trigger reboot if necessary
      meta: flush_handlers