---
- name: Install K3S on the Servers
  hosts: all
  become: true
  gather_facts: true

  tasks:
      - name: Create Config File
        template:
            src: config.yaml.j2
            backup: true
            dest: /etc/rancher/k3s/config.yaml
      - name: Install K3S
        get_url:
            url: https://get.k3s.io
        
#        curl -sfL https://get.k3s.io | K3S_TOKEN=12345 sh -s - server --flannel-backend none