apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: velero-s3-credentials
  namespace: velero
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/Infrastructure/items/K3S Velero - S3 Credentials
