apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: district-badges-prod
  namespace: argocd
spec:
  project: lbd-apps
  source:
    repoURL: https://github.com/LBDistrictScouts/DistrictBadges.git
    targetRevision: main
    path: K8S/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: district-badges-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
