apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: district-core-data
  namespace: argocd
spec:
  project: lbd-apps
  source:
    repoURL: https://github.com/LBDistrictScouts/DistrictCoreData.git
    targetRevision: main
    path: k8s
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: district-core-data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true

