apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: event-booking-backend
  namespace: argocd
spec:
  project: lbd-apps
  source:
    repoURL: https://github.com/LBDistrictScouts/EventBookingBackend.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: event-booking
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
